# S: Build Lifecycle
language: node_js

node_js:
- 0.1

branches:
  only:
  - blogSrc

before_install:
- npm install -g hexo

install:
- npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config --global user.name "todd zhang"
- git config --global user.email "phray.zhang@gmail.com"

env:
  global:
    - GH_REF: github.com/CloudsDocker/cloudsdocker.github.io.git
    - secure: "dwWaGINPrH4DUUCsdXulv6RIPL2fRuTGZXPUDQllO6E2CN8pw07ziKQ7MhZCMVBpCQXkuxm0JooHcGnJHj8XDUVYD3wnbQhNbKSl2fV+BwRIdDBHsmdU42WMNAlQR0zJ1v/+fqQx76N7YymrSxIOTvq0TLOnp2gxI7r/1qa+xwKOY7P5LsoW2jPu0sKxO/X/c8lxx+DZKRS6Ehv6f4ygGEw9RD1V1+NdCxlzlCYZ0coHGDr/+fK9HJ8G2qoaqfWy9aVznR6BnaPfIvnuu+mTIehBlqMzq1Rh3DuGL3iCvRCNg1R6oMPWn8LKHbn7PNKbZmFllR3TQiuVIk3yEH5pTLHz1KlnIc9XSOSOKkmdEHYWrA0Z3SNNXulQBXZ1VEGFKEIFPS7e67xfz0+ghpbRSPDzD/TsrWRLf+ACeuhh2QAzdQPPTjJOsqrZznJpr9Alp5kqMk/qAqTJbvbtSDKaiNdk9q5htFzoYTyiCJIQI6ZbX+9+KC1I2Qdp9nLO4n+sFPO39N4Gvq/58Aah052CBXZg9d5R4ySg1IoBPPYBhn7TlzBCWeYZ+lPksuCVEXNN3LrKsgHAoCLQywCvgRuhK9gCR7+VbcrENvdy7M5j+28oi991BqBY0LQOtdQRp/dsQg8iMpElpMKKYLKGRjUh8AXqtaxJt2LQSnWQByosG5g="


script:
- mkdir .deploy
- mkdir .publish
- cd .deploy
- echo $DEPLOY_REPO
- echo ${GH_TOKEN}
- pwd
- ls -lt
- git clone --depth 1 --branch blogSrc --single-branch $DEPLOY_REPO . || (git init && git remote add -t blogSrc origin $DEPLOY_REPO)
- ls -lt
- hexo clean
- ls -lt
- hexo generate
- ls -lt
#- ls -lt ./public/
- cd ../.publish
# - touch README
- ls -lt
- git init && git remote add origin $DEPLOY_REPO
- git pull origin master
- cp -r -f ../.deploy/* .
- ls -lt
#- git pull origin master
- git status
- git add .
- git commit -am 'Site updated from travis'
#- git push -f
- git push -f "https://${GH_TOKEN}@${GH_REF}" origin master
- git status

after_success:


# E: Build LifeCycle

# end by todzhang
