# S: Build Lifecycle
language: node_js

node_js:
- 0.1

branches:
  only:
  - master

before_install:
- npm install -g hexo

install:
- npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config user.name "todd zhang"
- git config user.email "phray@163.com"

env:
  global:
    - GH_REF: CloudsDocker/cloudsdocker.github.io
    - secure: "dwWaGINPrH4DUUCsdXulv6RIPL2fRuTGZXPUDQllO6E2CN8pw07ziKQ7MhZCMVBpCQXkuxm0JooHcGnJHj8XDUVYD3wnbQhNbKSl2fV+BwRIdDBHsmdU42WMNAlQR0zJ1v/+fqQx76N7YymrSxIOTvq0TLOnp2gxI7r/1qa+xwKOY7P5LsoW2jPu0sKxO/X/c8lxx+DZKRS6Ehv6f4ygGEw9RD1V1+NdCxlzlCYZ0coHGDr/+fK9HJ8G2qoaqfWy9aVznR6BnaPfIvnuu+mTIehBlqMzq1Rh3DuGL3iCvRCNg1R6oMPWn8LKHbn7PNKbZmFllR3TQiuVIk3yEH5pTLHz1KlnIc9XSOSOKkmdEHYWrA0Z3SNNXulQBXZ1VEGFKEIFPS7e67xfz0+ghpbRSPDzD/TsrWRLf+ACeuhh2QAzdQPPTjJOsqrZznJpr9Alp5kqMk/qAqTJbvbtSDKaiNdk9q5htFzoYTyiCJIQI6ZbX+9+KC1I2Qdp9nLO4n+sFPO39N4Gvq/58Aah052CBXZg9d5R4ySg1IoBPPYBhn7TlzBCWeYZ+lPksuCVEXNN3LrKsgHAoCLQywCvgRuhK9gCR7+VbcrENvdy7M5j+28oi991BqBY0LQOtdQRp/dsQg8iMpElpMKKYLKGRjUh8AXqtaxJt2LQSnWQByosG5g="


script:
- hexo generate


after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:master


# E: Build LifeCycle


