# Site settings
title: Highly Distinguish
subtitle: "IT solution & education"
email: phray.zhang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Highly Distinguish pty. ltd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://todzhang.com"
twitter_username: CloudsDocker
github_username: CloudsDocker
google_analytics: G-MP843S92NP

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
teaser: /assets/images/Todd_Stamp_Logo.png

# Site configuration
locale: "en-US"
search: true
search_full_content: true

# Add explicit permalink structure
permalink: /:categories/:title/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-96218029-2"
    anonymize_ip: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache  
  - jekyll-sitemap
  - jekyll-seo-tag
  

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true