baseURL = "http://example.org/"
languageCode = "en-us"
title = "Clouds&Docker"
theme = "ananke"
#theme = "m10c"
googleAnalytics = "UA-96218029-1"
enableEmoji = true
email = "phray.zhang@gmail.com"

[params]
  background_color_class = "bg-black"
  description = "by Todd"
  featured_image = "/images/DonotJump.jpeg"
  show_reading_time = true
  github = "https://github.com/CloudsDocker"
  enableEmoji = true
  email = "phray.zhang@gmail.com"