baseURL = "http://todzhang.com/"
languageCode = "en-us"
title = "Clouds&Docker"
theme = "ananke"
#theme = "m10c"
googleAnalytics = "UA-96218029-2"
enableEmoji = true
email = "phray.zhang@gmail.com"
featured_image = "/images/DonotJump.jpeg"

[params]
  background_color_class = "bg-black"
  description = "by Todd"
  featured_image = "/images/DonotJump.jpeg"
  show_reading_time = true
  github = "https://github.com/CloudsDocker"
  enableEmoji = true
  email = "phray.zhang@gmail.com"

[deployment]
[[deployment.targets]]
# An arbitrary name for this target.
name = "myAWSDeployment"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://todzhang.com?region=ap-southeast-2"
# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.

cloudFrontDistributionID = "E2M5SPPZZJOVL8"